/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * USART 2->STLINK
 *
 * TX->PA2
 * RX->PA3
 *
 */

#include <string.h>
#include "stm32f446xx.h"

char packets_keys[] = {'V','C','F','D','Z','S','X','N'};
uint32_t packets_value[5];

uint8_t status = 0b00000011;
uint8_t frequency = 96;

uint8_t heartbeat[5];
uint8_t telemetry[35];

uint8_t comm[3];

uint8_t dma_ready;
uint8_t telemetry_status;
uint8_t heartbeat_status;

char receive_data[1000];

void executeCommand(uint8_t command)
{
	status = command;
}

uint8_t validatePacket(char s)
{
	uint8_t x;
	for(x = 0; packets_keys[x] != s; x++);
	return packets_keys[x];
}

uint32_t getValue_Variable(char s)
{
	uint8_t x;
	for(x = 0; packets_keys[x] != s; x++);
	return packets_value[x];
}

void addValue_Variable(char s, uint8_t message[7])
{
	int x;
	for(x = 0; packets_keys[x] != s; x++);
	for(int y = 2; y < 6; y++)
	{
		packets_value[x] |= (message[x] << (y-2)*8) & 0xFF;
	}
}

void heartbeatStructure(void)
{
	heartbeat[0] = '$';
	heartbeat[1] = 'S';
	heartbeat[2] = 2;
}

void telemetryStructure(void)
{
	telemetry[0] = '$';
	telemetry[1] = 'V';
	telemetry[2] = 4;
	telemetry[7] = '$';
	telemetry[8] = 'C';
	telemetry[9] = 4;
	telemetry[14] = '$';
	telemetry[15] = 'F';
	telemetry[16] = 4;
	telemetry[21] = '$';
	telemetry[22] = 'D';
	telemetry[23] = 4;
	telemetry[28] = '$';
	telemetry[29] = 'Z';
	telemetry[30] = 4;
}

USART_Handle_t USART2Handle;

TIM_Handle_t TIM3Handle ;

GPIO_Handle_t LED;

DMA_Handle_t DMA1Handle;

void LED_GPIOInits(void)
{
	LED.pGPIOx = GPIOA;
	LED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	//LED.GPIO_PinConfig.GPIO_PinAltFunMode = 2;
	LED.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	LED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	LED.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	//LED D13
	LED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	GPIO_Init(&LED);
}

void TIM3_Inits(TIM_Handle_t *pTIM3Handle)
{
	pTIM3Handle->pTIMx = TIM3;
	pTIM3Handle->TIM_Config.TIM_AutoReloadPreload = TIM_ARPE_ENABLE;
	pTIM3Handle->TIM_Config.TIM_CLKDivision = TIM_CKD_DIV1;
	pTIM3Handle->TIM_Config.TIM_CNTMode = TIM_UPCOUNT_MODE;
	pTIM3Handle->TIM_Config.TIM_Frequency = 1000;
	pTIM3Handle->TIM_Config.TIM_IntEnable = TIM_IT_ENABLE;
	pTIM3Handle->TIM_Config.TIM_MasterModeSel = TIM_MMS_UPDATE;

	TIM_Init(pTIM3Handle);
}

void USART2_GPIOInits(void)
{
	GPIO_Handle_t USART2pin;
	USART2pin.pGPIOx = GPIOA;
	USART2pin.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	USART2pin.GPIO_PinConfig.GPIO_PinAltFunMode = 7;
	USART2pin.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	USART2pin.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	USART2pin.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	//TX
	USART2pin.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_2;
	GPIO_Init(&USART2pin);
	//RX
	USART2pin.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_3;
	GPIO_Init(&USART2pin);
}

void USART2_Inits(USART_Handle_t *pUSART2Handle)
{
	pUSART2Handle->pUSARTx = USART2;
	pUSART2Handle->USARTConfig.USART_Baud = 2200000;
	pUSART2Handle->USARTConfig.USART_HWFlowControl = USART_HW_FC_NONE;
	pUSART2Handle->USARTConfig.USART_Mode = USART_MODE_TX_RX;
	pUSART2Handle->USARTConfig.USART_NoOfStopBits = USART_1_STOPBITS;
	pUSART2Handle->USARTConfig.USART_ParityControl = USART_PARITY_DISABLE;
	pUSART2Handle->USARTConfig.USART_WordLength = USART_WLEN_8BITS;
	pUSART2Handle->USARTConfig.USART_DMA = USART_DMA_TX;

	USART_Init(pUSART2Handle);
}

void DMA1_Inits(DMA_Handle_t *pDMA1Handle)
{
	pDMA1Handle->pDMAx = DMA1;
	pDMA1Handle->DMA_stream = 6;
	pDMA1Handle->DMA_Config.DMA_Channel = DMA_CHANNEL_4;
	pDMA1Handle->DMA_Config.DMA_Direction = DMA_DIR_MEM_TO_PERIPH;
	pDMA1Handle->DMA_Config.DMA_Priority = DMA_PRIORITY_MEDIUM;
	pDMA1Handle->DMA_Config.DMA_MemDataSize = DMA_DATA_SIZE_BYTE;
	pDMA1Handle->DMA_Config.DMA_PeriphDataSize = DMA_DATA_SIZE_BYTE;
	pDMA1Handle->DMA_Config.DMA_MemInc = ENABLE;
	pDMA1Handle->DMA_Config.DMA_PeriphInc = DISABLE;
	pDMA1Handle->DMA_Config.DMA_FIFOMode = DMA_FIFO_MODE_DISABLED;
	pDMA1Handle->DMA_Config.DMA_FIFOThreshold = 0;
	pDMA1Handle->DMA_Config.DMA_Mode = DMA_MODE_NORMAL;
	pDMA1Handle->DMA_Config.DMA_TransferIT = ENABLE;
	pDMA1Handle->BufferSize = 4;

	DMA_Init(pDMA1Handle);
}

void USART_HeartBeatTX(void);
void USART_TelemetryTX(void);
void USART_CommandBack(uint8_t c1, uint8_t c2, uint8_t c3);

int main(void)
{
	packets_value[0] = 120;
	packets_value[1] = 110;
	packets_value[2] = 200;
	packets_value[3] = 220;

	SystemCLK_Config_84MHz();

	SCB_CPACR |= ((3UL << 10*2) | (3UL << 11*2)); //FPU Enabled

    USART2_GPIOInits();
	USART2_Inits(&USART2Handle);
	USART_PeripheralControl(USART2Handle.pUSARTx, ENABLE);

	USART_IRQInterruptConfig(IRQ_NO_USART2,ENABLE);
	USART_IRQPriorityConfig(IRQ_NO_USART2,NVIC_IRQ_PRI15);

	memset(receive_data, 0, sizeof(receive_data));
	USART_ReceiveDataWithIT(&USART2Handle,(uint8_t *)receive_data, 3);

	//TIM3_GPIOInits();
	TIM3_Inits(&TIM3Handle);

	TIM_IRQInterruptConfig(IRQ_NO_TIM3,ENABLE);
	TIM_IRQPriorityConfig(IRQ_NO_TIM3,NVIC_IRQ_PRI10);

	LED_GPIOInits();

	TIM_Start(&TIM3Handle);

	//DMA 1 Stream 6 Channel 4
	DMA1_Inits(&DMA1Handle);
	DMA_IRQInterruptConfig(IRQ_NO_DMA1_STREAM6,ENABLE);
	DMA_IRQPriorityConfig(IRQ_NO_DMA1_STREAM6,NVIC_IRQ_PRI1);

	heartbeatStructure();
	telemetryStructure();

	dma_ready = ENABLE;

	while(1)
	{
		if(dma_ready == ENABLE)
		{
			if(telemetry_status == ENABLE)
			{
				dma_ready = DISABLE;
				USART_TelemetryTX();
				//USART_CommandBack(receive_data[0], receive_data[1], receive_data[2]);
			}else if(heartbeat_status == ENABLE)
			{
				dma_ready = DISABLE;
				USART_HeartBeatTX();
			}
		}
	}
	return 0;
}

void USART_CommandBack(uint8_t c1, uint8_t c2, uint8_t c3)
{
	//while(!(USART2Handle.pUSARTx->SR & USART_SR_TC));
	USART_ClearFlag(USART2Handle.pUSARTx, USART_TC_FLAG);
	comm[0] = c1;
	comm[1] = c2;
	comm[2] = c3;

	DMA_SetAddresses(&DMA1Handle, (void*)comm, (void*)&USART2Handle.pUSARTx->DR);
	DMA_ConfigureBuffer(&DMA1Handle, 3);
	DMA_StartTransfer(&DMA1Handle);
	telemetry_status = DISABLE;
	memset(receive_data, 0, sizeof(receive_data));
}

void USART_DecodeRX(USART_Handle_t *pUSARTHandle)
{
	if(receive_data[0] == '$')
	{
		if(receive_data[1] == 'X')
		{
			//executeCommand(receive_data[2]);
		}
	}
	memset(receive_data, 0, sizeof(receive_data));
}

void USART_HeartBeatTX(void)
{
	//while(!(USART2Handle.pUSARTx->SR & USART_SR_TC));
	USART_ClearFlag(USART2Handle.pUSARTx, USART_TC_FLAG);
	heartbeat[3] = status;
	heartbeat[4] = frequency;

	DMA_SetAddresses(&DMA1Handle, (void*)heartbeat, (void*)&USART2Handle.pUSARTx->DR);
	DMA_ConfigureBuffer(&DMA1Handle, 5);
	DMA_StartTransfer(&DMA1Handle);
	heartbeat_status = DISABLE;
}

void USART_TelemetryTX(void)
{
	//while(!(USART2Handle.pUSARTx->SR & USART_SR_TC));
	USART_ClearFlag(USART2Handle.pUSARTx, USART_TC_FLAG);
	telemetry[3] = getValue_Variable('V') >> 24;
	telemetry[4] = (getValue_Variable('V') >> 16) & 0xFF;
	telemetry[5] = (getValue_Variable('V') >> 8) & 0xFF;
	telemetry[6] = (getValue_Variable('V')) & 0xFF;

	telemetry[10] = getValue_Variable('C') >> 24;
	telemetry[11] = (getValue_Variable('C') >> 16) & 0xFF;
	telemetry[12] = (getValue_Variable('C') >> 8) & 0xFF;
	telemetry[13] = (getValue_Variable('C')) & 0xFF;

	telemetry[17] = getValue_Variable('F') >> 24;
	telemetry[18] = (getValue_Variable('F') >> 16) & 0xFF;
	telemetry[19] = (getValue_Variable('F') >> 8) & 0xFF;
	telemetry[20] = (getValue_Variable('F')) & 0xFF;

	telemetry[24] = getValue_Variable('D') >> 24;
	telemetry[25] = (getValue_Variable('D') >> 16) & 0xFF;
	telemetry[26] = (getValue_Variable('D') >> 8) & 0xFF;
	telemetry[27] = (getValue_Variable('D')) & 0xFF;

	telemetry[31] = getValue_Variable('Z') >> 24;
	telemetry[32] = (getValue_Variable('Z') >> 16) & 0xFF;
	telemetry[33] = (getValue_Variable('Z') >> 8) & 0xFF;
	telemetry[34] = (getValue_Variable('Z')) & 0xFF;

	DMA_SetAddresses(&DMA1Handle, (void*)telemetry, (void*)&USART2Handle.pUSARTx->DR);
	DMA_ConfigureBuffer(&DMA1Handle, 35);
	DMA_StartTransfer(&DMA1Handle);
	telemetry_status = DISABLE;
}

void TIM3_IRQHandler(void)
{
	heartbeat_status = ENABLE;
	TIM_IRQHandling(&TIM3Handle);
}

void USART2_IRQHandler(void)
{
	USART_IRQHandling(&USART2Handle);
}

void USART_ApplicationEventCallback(USART_Handle_t *pUSARTHandle,uint8_t ApEv)
{
	if(ApEv == USART_EVENT_RX_CMPLT)
	{
		telemetry_status = ENABLE;
		//USART_DecodeRX(pUSARTHandle);
		USART_ReceiveDataWithIT(&USART2Handle,(uint8_t *)receive_data, 3);
	}else if (ApEv == USART_EVENT_TX_CMPLT)
	{
		;
	}
}

void DMA_ApplicationEventCallback(DMA_Handle_t *pDMAHandle, uint8_t ApEv)
{
	if(ApEv == DMA_EVENT_TCIF_CMPLT)
	{
		DMA_StopTransfer(&DMA1Handle);
		dma_ready = ENABLE;
		if(heartbeat_status == ENABLE)
		{
			//telemetry_status = DISABLE;
		}else
		{
			//telemetry_status = ENABLE;
		}

	}
}

void DMA1_Stream6_IRQHandler(void)
{
	DMA_IRQHandling(&DMA1Handle);
}
